---
title: "R Notebook"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---

```{r}
library(purrr)
library(dplyr)
new_col <- unlist(all_common_col)

shrink <- function(country){
  country <- country[, new_col]
  return(country)
}


argentina  <- shrink(argentina)
belize  <- shrink(belize)
bolivia  <- shrink(bolivia)
brazil  <- shrink(brazil)
canada  <- shrink(canada)
chile  <- shrink(chile)
colombia  <- shrink(colombia)
costa <- shrink(costa)
ecuador <- shrink(ecuador)
elsalvador <- shrink(elsalvador)
guatemala <- shrink(guatemala)
#guyana <- shrink(guyana) Commented out because it is English-only
honduras <- shrink(honduras)
#jamaica <- shrink(jamaica) Commented out because it is English-only
mexico <- shrink(mexico)
nicaragua <- shrink(nicaragua)
panama <- shrink(panama)
paraguay <- shrink(paraguay)
peru <- shrink(peru)
suriname <- shrink(suriname)
usa <- shrink(usa)
uruguay <- shrink(uruguay)
venezuela <- shrink(venezuela)
```


Shrink to any of the number of columns that are wanted, needs to happen before the columns are edited, with make everything take less time

```{r}

new_col <- unlist(common_in_2016)

shrink <- function(country){
  country <- country[, new_col]
  return(country)
}


venezuela_2016_17  <- shrink(venezuela_2016_17)
bolivia_2016_17  <- shrink(bolivia_2016_17)
brazil_2016_17  <- shrink(brazil_2016_17)
canada_2016_17  <- shrink(canada_2016_17)
chile_2016_17  <- shrink(chile_2016_17)
colombia_2016_17  <- shrink(colombia_2016_17)
costa_2016_17  <- shrink(costa_2016_17)
ecuador_2016_17  <- shrink(ecuador_2016_17)
elsalvador_2016_17  <- shrink(elsalvador_2016_17)
guatemala_2016_17  <- shrink(guatemala_2016_17)
guyana_2016_17  <- shrink(guyana_2016_17)
honduras_2016_17  <- shrink(honduras_2016_17)
jamaica_2016_17  <- shrink(jamaica_2016_17)
mexico_2016_17  <- shrink(mexico_2016_17)
nicaragua_2016_17  <- shrink(nicaragua_2016_17)
panama_2016_17  <- shrink(panama_2016_17)
paraguay_2016_17 <- shrink(paraguay_2016_17)
peru_2016_17  <- shrink(peru_2016_17)
usa_2016_17  <- shrink(usa_2016_17)
uruguay_2016_17  <- shrink(uruguay_2016_17)
```

