---
title: "Exploring Tidy Data"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---

##Lengthening the data set
```{r}
library(tidyverse)
library(devtools)
library(fs)

#Function for reducing columns
lengthen <- function(country) {
  country <- country %>%
  select(-strata) %>%
  gather(column_name, answer, estratopri:gi7r) %>%
  select(pais, year, unique_id, column_name, answer)
  return(country)
}

#argentina <- lengthen(argentina)
```

##Applying above functions to every country
```{r}
#Adds all the countries, in correct tidy format into a large data set

library(purrr)
uruguay_and_venezuela <- list(uruguay, venezuela)
uruguay_and_venezuela <- map_df(uruguay_and_venezuela, lengthen)

argentina_and_belize <- list(argentina, belize)
argentina_and_belize <- map_df(argentina_and_belize, lengthen)

bolivia_and_brazil <- list(bolivia, brazil)
bolivia_and_brazil <- map_df(bolivia_and_brazil, lengthen)

canada_and_chile <- list(canada, chile)
canada_and_chile <- map_df(canada_and_chile, lengthen)

colombia_and_costa <- list(colombia, costa)
colombia_and_costa <- map_df(colombia_and_costa, lengthen)

ecuador_and_elsalvador <- list(ecuador, elsalvador)
ecuador_and_elsalvador <- map_df(ecuador_and_elsalvador, lengthen)

#guatemala_and_guyana <- list(guatemala, guyana)
#guatemala_and_guyana <- map_df(guatemala_and_guyana, lengthen)

#honduras_and_jamaica <- list(honduras, jamaica)
#honduras_and_jamaica <- map_df(honduras_and_jamaica, lengthen)

guatemala_and_honduras <- list(guatemala, honduras)
guatemala_and_honduras <- map_df(guatemala_and_honduras, lengthen)

mexico_and_nicaragua <- list(mexico, nicaragua)
mexico_and_nicaragua <- map_df(mexico_and_nicaragua, lengthen)

panama_and_peru <- list(panama, peru)
panama_and_peru <- map_df(panama_and_peru, lengthen)

suriname_and_usa <- list(suriname, usa)
suriname_and_usa <- map_df(suriname_and_usa, lengthen)

uruguay_and_venezuela <- list(uruguay, venezuela)
uruguay_and_venezuela <- map_df(uruguay_and_venezuela, lengthen)

paraguay <- lengthen(paraguay)

countries <- list(argentina,belize, bolivia, brazil, canada, chile, colombia, costa, ecuador, elsalvador, guatemala, honduras, mexico, nicaragua, panama, peru, suriname, usa, uruguay, venezuela)
tidy_data <- map_dfr(countries, lengthen)
#Then adds a column to the merged data set that distinguishes if the question is universal or not
#Removed Guayan and Jamaica 6/27

# everything <- everything %>%
#   mutate(common = column_name %in% all_common_col)
```

```{r}
write_csv(tidy_data, "tidy_data.csv")
```


```{r}
library(purrr)

countries_2016 <- list(venezuela_2016_17, bolivia_2016_17, brazil_2016_17, canada_2016_17, chile_2016_17, colombia_2016_17,costa_2016_17, ecuador_2016_17, elsalvador_2016_17, guatemala_2016_17, guyana_2016_17, honduras_2016_17, jamaica_2016_17, mexico_2016_17, nicaragua_2016_17, panama_2016_17, paraguay_2016_17, peru_2016_17, usa_2016_17, uruguay_2016_17)

every_2016 <- map_dfr(countries_2016, shrink)
```

```{r}
library(tidyr)
library(tidyverse)
library(dplyr)

try <- function(x){
  x <- x %>% 
    group_by(column_name) %>%
    mutate(grouped_id = row_number())
  x %>%
    spread(key = column_name, value = answer) %>%
    select(-grouped_id)
}

argentina_and_belize <- argentina_and_belize %>%
  spread(key = column_name, value = answer)
  x <- x %>% group_by(column_name) %>% mutate(grouped_id = row_number())
  x %>% spread(key = questions, value = answer) %>% select(-grouped_id)
}

bolivia(try)

#argentina_and_belize <- argentina_and_belize %>% spread(key = questions, value = answer)


#skipped because Error: Each row of output must be identified by a unique combination of keys

bolivia_and_brazil <- try(bolivia_and_brazil)
canada_and_chile <- try(canada_and_chile)


colombia_and_costa <- try(colombia_and_costa)

ecuador_and_elsalvador <- try(ecuador_and_elsalvador)
guatemala_and_guyana <- try(guatemala_and_guyana)

first_four <- bind_rows(argentina_and_belize, bolivia_and_brazil)

second_four <- bind_rows(canada_and_chile, colombia_and_costa)
first_and_second <- bind_rows(first_four, second_four)

third_four <- bind_rows(ecuador_and_elsalvador, guatemala_and_guyana)

honduras_and_jamaica <- try(honduras_and_jamaica)
mexico_and_nicaragua <- try(mexico_and_nicaragua)

fourth_four <- bind_rows(honduras_and_jamaica, mexico_and_nicaragua)

third_and_fourth <- bind_rows(third_four, fourth_four)

panama_and_peru <- try(panama_and_peru)
 
suriname_and_usa <- try(suriname_and_usa)

fifth_four <- bind_rows(panama_and_peru, suriname_and_usa)

uruguay_and_venezuela <- try(uruguay_and_venezuela)

sixth_four <- bind_rows(fifth_four, uruguay_and_venezuela)

paraguay <- try(paraguay)

last <- bind_rows(sixth_four, paraguay)

first_half <- bind_rows(first_and_second, third_and_fourth)

last_combine <- bind_rows(first_half, last)

write_csv(last_combine, "combined_tidy.csv")
```

```{r}
library(tidyr)
library(tidyverse)
library(dplyr)

try <- function(x){
  x <- x %>% group_by(column_name) %>% mutate(grouped_id = row_number())
  x %>% spread(key = questions, value = answer) %>% select(-grouped_id, -column_name)
}

bolivia <- try(bolivia)
```




```{r}
library(haven)
attributes(argentina_and_belize$pais)
```
