---
title: "clean 6-combining"
output: html_notebook
---
SEVEN

I thought about what would be the easiest way to work with the vb, and I decided that it would be easier to do the column manipulation before we lengthen - like what we did with the ids and NAs. I originally added it as 3.5, but this for some reason didn't work, so I tested around with somethings and then tested it out at 2.5, which then worked.


```{r}
library(tidyr)
library(tidyverse)
long_questions <- function(country, country_before, column){
			  #Starting at index 1
			  i <- 1
number_for_dupID <- rep(NA, column)
new_list <- rep(NA, column)
#Replaces original column names with readable version
			  while(i <= column){
			    #Isolates original column names
			    original <- (country$column_name)[i]
			    #Replaces with label
			    new <- attributes(country_before[[original]])$label
			    #Adds object to list
			    new_list[i] <- new
			    #Moves to next item
			    i <- i + 1
			  }
			  new_list
			}
lengthen <- function(country) {
			  country_before <- country
			  country <- country %>%
 #These are excluded because they are repeated
			  select(-strata,-sex, -vb11_10, -vb11_12) %>%
			  #Brings together the following columns
			  gather(column_name, answer, estratopri:vb_combined)
#Takes length of column_name and arguments from long_questions
			  column <- length(country$column_name)
			  questions <- long_questions(country, country_before, column)
 country <- country %>% 
			    mutate(questions)
country <- country %>% 
			    select(pais, year, unique_id, column_name, answer, questions, extra_id)
			  return(country)
			}

```


```{r}
costa_wide <- tidy_spread(lengthen(costa))
```


```{r}
og <- (argentina_long$column_name)[1]
argentina[[og]]
```


```{r}
tidy_spread <- function(x){
  x <- x %>%
    select(-column_name) %>%
    spread(questions, answer)
}
```


```{r}
argentina_wide <- tidy_spread(lengthen(argentina))
belize_wide <- tidy_spread(lengthen(belize))
brazil_wide <- tidy_spread(lengthen(brazil))
chile_wide <- tidy_spread(lengthen(chile))
panama_wide <- tidy_spread(lengthen(panama))
paraguay_wide <- tidy_spread(lengthen(paraguay))
peru_wide <- tidy_spread(lengthen(peru))
suriname_wide <- tidy_spread(lengthen(suriname))
uruguay_wide <- tidy_spread(lengthen(uruguay))
venezuela_wide <- tidy_spread(lengthen(venezuela))
bolivia_wide <- tidy_spread(lengthen(bolivia))
canada_length <- lengthen(canada)
canada_wide <- tidy_spread(canada_length)
colombia_length <- lengthen(colombia)
colombia_wide <- tidy_spread(colombia_length)
costa_wide <- tidy_spread(lengthen(costa))
ecuador_wide <- tidy_spread(lengthen(ecuador))
elsalvador_wide <- tidy_spread(lengthen(elsalvador))
guatemala_wide <- tidy_spread(lengthen(guatemala))
honduras_wide <- tidy_spread(lengthen(honduras))
mexico_wide <- tidy_spread(lengthen(mexico))
nicaragua_wide <- tidy_spread(lengthen(nicaragua))
usa_wide <- tidy_spread(lengthen(usa))
```


```{r}
suriname_long <- lengthen(suriname)
```

```{r}
Error: Each row of output must be identified by a unique combination of keys. Keys are shared for 14012 rows: * 554606, 918918 * 554825, 919137 * 553905, 918217 * 554698, 919010 * 553578, 917890 * 553551, 917863 * 553780, 918092 * 553918, 918230 * 554694, 919006 * 553981, 918293 * 553498, 917810 * 554628, 918940 * 554799, 919111 * 553582, 917894 * 554293, 918605 * 554907, 919219 * 554669, 918981 * 554396, 918708 * 554085, 918397 * 554781, 919093 * 554686, 918998 * 553773, 918085 * 554209, 918521 * 553890, 918202 * 554755, 919067 * 554323, 918635 * 554006, 918318 * 553793, 918105 * 554508, 918820 * 554082, 918394 * 554074, 918386 * 553909, 918221 * 554103, 918415 * 553636, 917948 * 554022, 918334 * 554554, 918866 * 553777, 918089 * 553864, 918176 * 553641, 917953 * 554528, 918840 * 554060, 918372 * 554659, 918971 * 553614, 917926 * 553685, 917997 * 554818, 919130 * 554586, 918898 * 554455, 918767 * 554404, 918716 * 554580, 918892 * 554650, 918962 * 554913, 919225 * 554576, 918888 * 554
```


```{r}
library(tidyr)
library(tidyverse)
library(dplyr)


argentina_and_belize <- bind_rows(argentina_wide, belize_wide)
bolivia_and_brazil <- bind_rows(bolivia_wide, brazil_wide)
canada_and_chile <- bind_rows(canada_wide, chile_wide)
colombia_and_costa <- bind_rows(colombia_wide, costa_wide)
ecuador_and_elsalvador <- bind_rows(ecuador_wide, elsalvador_wide)
guatemala_and_honduras <- bind_rows(guatemala_wide, honduras_wide)
mexico_and_nicaragua <- bind_rows(mexico_wide, nicaragua_wide)
panama_and_peru <- bind_rows(panama_wide, peru_wide)
suriname_and_usa <- bind_rows(suriname_wide, usa_wide)
uruguay_and_venezuela <- bind_rows(uruguay_wide, venezuela_wide)

  
first_four <- bind_rows(argentina_and_belize, bolivia_and_brazil)
second_four <- bind_rows(canada_and_chile, colombia_and_costa)
first_and_second <- bind_rows(first_four, second_four)

third_four <- bind_rows(ecuador_and_elsalvador, guatemala_and_honduras)
third_and_fourth <- bind_rows(third_four, mexico_and_nicaragua)

fifth_four <- bind_rows(panama_and_peru, suriname_and_usa)
sixth_four <- bind_rows(fifth_four, uruguay_and_venezuela)
last <- bind_rows(sixth_four, paraguay)

first_half <- bind_rows(first_and_second, third_and_fourth)

last_combine <- bind_rows(first_half, last)

write_csv(last_combine, "combined_tidy.csv")
```
