---
title: "Exploring Tidy Data"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---

##Combining idnum
```{r}
#Combines idnum and idnum_14 with "/"
combine_id <- function(country) {
      mutate(country, idnum = ifelse(idnum_14 == '', idnum, paste(idnum,idnum_14,sep = "/")))
}
```


##Lengthening the data set
```{r}
library(tidyverse)
library(devtools)
library(fs)

#Function for reducing columns
lengthen <- function(country) {
  country <- combine_id(country)
  country <- country %>%
  gather(column_name, answer, estratopri:formatq) %>%
  select(pais, year, idnum, column_name, answer)
}

<<<<<<< HEAD
=======

>>>>>>> c26cc21cf225696fd0120e9cd1bda731ad39764b

```

##Applying above functions to every country
```{r}
#Adds all the countries, in correct tidy format into a large data set

library(purrr)
countries <- list(argentina,belize, bolivia, brazil, canada, chile, colombia, costa, ecuador, elsalvador, guatemala, guyana, honduras, jamaica, mexico, nicaragua, panama, peru, suriname, usa, uruguay, venezuela)

everything <- map_dfr(countries, lengthen)
<<<<<<< HEAD
=======

#Then adds a column to the merged data set that distinguishes if the question is universal or not
>>>>>>> c26cc21cf225696fd0120e9cd1bda731ad39764b

everything <- everything %>% mutate(common = column_name %in% all_common_col)


```


```{r}
write.csv(everything, file = "LAPOP_everything_test.csv")
```



