---
title: "Questions as columns"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---

This will add the full questions to the column names. This should happen between steps 5 and 6.
```{r}
#Creating a list of 149 empty NA values
questions <- rep(NA,149)

#Collecting attributes of Argentina's column, pais, into separate object
pais <- attributes(argentina$pais)

#Isolated the label "País"
pais_label <- pais$label

#Renaming first index of questions list to "País"
questions[1] <- pais_label

#Repeating same process with column "year"
year <- attributes(argentina$year)
year <- year$label
questions[2] <- year

x <- 6
i <- 3

#Begins at 6th index of all_common_col list
original <- all_common_col[[x]]

#Renames old column placeholder
new <- attributes(argentina[[original]])$label
questions[i] <- new

#Moves to next spot in list
x <- x + 1
i <- i + 1

#Loops through all items in all_common_col list and replaces old column name with full question
while(x < 152){
  original <- all_common_col[[x]]
  new <- attributes(argentina[[original]])$label
  x <- x + 1
  questions[i] <- new
  i <- i + 1
  
}
questions[149] <- "Unique ID"
```
I renamed spot to original for clarification and added comments for readbility.


```{r}
library(tidyverse)
library(devtools)
library(fs)

long_questions <- function(country, country_before, column){
  i <- 1
  new_list <- rep(NA, column)
  while(x < column){
    spot <- (country$column_name)[x]
    new <- attributes(country_before[[spot]])$label
    new_list[i] <- new
    i <- i + 1
    x <- x + 1
  }
  new_list
}

#Function for reducing columns
lengthen <- function(country) {
  country_before <- country
  country <- country %>%
  select(-strata) %>%
  gather(column_name, answer, estratopri:gi7r)
  column <- length(country$column_name)
  questions <- long_questions(country, country_before, column)
  country <- country %>% mutate(questions)
  country <- country %>% select(pais, year, unique_id, column_name, answer, questions)
  return(country)
}

argentina <- lengthen(argentina)
belize <- lengthen(belize)




```


